include/dpdk.h, src/ctrl.c, src/ip_vs_dest.c, src/ip_vs_wlc.c, src/ipv4.c
=> clean tabs in code

README.md
1. add test env description.
2. add git clone link for DPVS.
=> update README: add build/test environment.

src/netif.c
on same arch, NIC bound to numa node -1:
```bash
cat /sys/bus/pci/devices/0000\:01\:00.1/numa_node
-1
```
and `dpvs` exit exceptionally
```bash
EAL: Error - exiting with code: 1
Cause: add KNI port fail, exiting...
```
=> netif: dpvs exits if NIC bound to numa node -1

include/conf/netif.h, include/mbuf.h, include/netif.h, src/ip_vs_core.c, src/mbuf.c, src/netif.c, tools/dpip/link.c
Add flag to enable/disable packet capturing through kni device.
When enabled, all packets TX/RX will be copied and passed to KNI.
It's for debug only, and will affect the performance significantly.
=> netif: packet capturing support by kni for debug.

conf/dpvs.conf.items, src/netif.c
default value of netif_defs/device/tx/descriptor_number changed from 64->256
default value of netif_defs/device/tx/descriptor_number changed from 128->512
note that both rx and tx descriptor_number  are set to 1024 in /etc/dpvs.conf*.sample
=> conf: fix invalid configuration 'netif_defs/device/tx/descriptor_number'

doc/TODO.md, tools/Makefile
1. on some env, `pushd` is not supported, so use `cd -` to get back.
2. add todo list for short-term and long-term plan.
=> Add todo list and fix build where pushd not support.

include/ipvs/proto_icmp.h, src/ipvs/ip_vs_conn.c, src/ipvs/ip_vs_proto_icmp.c
Add status of icmp session for ipvsadm -lc optimize the unkown status info of tcp/udp sessions.
=> Add status of icmp session for ipvsadm -lc optimize the unkown status info of tcp/udp sessions.

conf/dpvs.conf.sample, src/ipv4.c
Set it to off, and dpvs won't forward packets that don't match the rules.
=> Add a switch of ipv4_forward in ipv4_defs config section.

include/ipvs/dest.h, src/ipvs/ip_vs_conn.c, src/ipvs/ip_vs_dest.c, src/ipvs/ip_vs_service.c, src/ipvs/ip_vs_stats.c, src/neigh.c, tools/ipvsadm/ipvsadm.c, tools/keepalived/keepalived/vrrp/vrrp_ipaddress.c
1. fix assert and crash when `dest->svc` is NULL.
2. fix bug for choosing source ip for ARP request.
3. workaround: msg timeout problem when printing all session entries.
=> Fix crash for service, msg timeout and ARP issues.

src/inet.c, src/netif.c, tools/dpip/link.c
1. replace rte_pktmbuf_clone with mbuf_copy in netif_tx_burst since
rte_kni_tx_burst is changed in DPDK-17.05.2;
2. free the mbuf while kni_ingress is unnecessary due to forward2kni
flag is enable;
3. add error message for dpip link command;
=> netif: intergating with DPDK-17.05.2 in forward2kni mode and inet: bugfix

patch/dpdk-stable-17.05.2/0001-PATCH-kni-use-netlink-event-for-multicast-driver-par.patch
dev.ndo_set_rx_mode is in spin_lock_bh(), GFP_KERNEL will trigger
schedule, cannot be used. use GFP_ATOMIC instread.
=> patch: kni: use GFP_ATOMIC instead of GFP_KERNEL.

tools/keepalived/keepalived/check/check_data.c, tools/keepalived/keepalived/check/ipvswrapper.c, tools/keepalived/keepalived/check/ipwrapper.c, tools/keepalived/keepalived/core/global_data.c
1. Don't load kernel module in keepalived for dpvs.
2. Fix segmentation fault on starting keepalived without dpvs.
Thank you.
=> Don't load ip_vs kernel module and fix a segmentation fault.

tools/keepalived/keepalived/vrrp/vrrp_ipaddress.c
keepalived.conf
```bash
39     virtual_routes {
40         10.0.1.0/24 via 192.168.1.1 dev dpdk0
41     }
```
core dump
```bash
#0  ipaddresstos (ipaddress=0x0) at vrrp_ipaddress.c:98
98	vrrp_ipaddress.c: No such file or directory.
(gdb) bt
#0  ipaddresstos (ipaddress=0x0) at vrrp_ipaddress.c:98
#1  0x0000000000412548 in netlink_route (iproute=0x1ae6760, cmd=1) at vrrp_iproute.c:72
#2  0x0000000000412634 in netlink_rtlist (rt_list=0x1ad90a0, cmd=0, cmd@entry=1) at vrrp_iproute.c:100
#3  0x0000000000413694 in vrrp_handle_iproutes (cmd=cmd@entry=1, vrrp=0x1ad8d50, vrrp=0x1ad8d50) at vrrp.c:69
#4  0x0000000000413f75 in vrrp_state_become_master (vrrp=vrrp@entry=0x1ad8d50) at vrrp.c:766
#5  0x0000000000414443 in vrrp_state_master_tx (vrrp=vrrp@entry=0x1ad8d50, prio=prio@entry=0) at vrrp.c:923 …
```
=> keepalived: fix crash when 'virtual_routes' configured without src

tools/keepalived/keepalived/check/check_tcp.c, tools/keepalived/lib/scheduler.c
sometimes it release config item with Null pointer.
=> Fix another segmentation fault point.

include/conf/netif.h, src/netif.c, tools/dpip/link.c
use port name instead of ID to communicate between dpip and dpvs,
by @yuwenchao.
=> dpip/link: use port name instead of ID.

src/inetaddr.c, src/ip_tunnel.c
GCC was detecting trucated strings. This was corrected by specifying a
character limit in the string format of the print command.
=> Fix build failure with GCC-7

src/ctrl.c, src/netif.c
DPVS cannot work with over 64 CPUs now because dpvs multicast msg uses a 64-bit lcore mask. This change makes dpvs work on a server with over 64 CPUs  when DPVS_MAX_LCORE is not greater than 64.
=> netif: make dpvs work with over 64 CPUs

src/ipvs/ip_vs_conn.c
修改`ip_vs_conn.c`模块中的`conn_ctrl_term()`函数中的`sockopt_register` 为 `sockopt_unregister`
=> ipvs-conn: fix typo when unregister sockopt

src/dpdk.mk
Support Broadcom NIC driver rte_pmd_bnxt.
=> dpdk.mk: support BCM driver rte_pmd_bnxt

conf/dpvs.conf.items, include/uoa.h, src/ipvs/ip_vs_proto_udp.c, uoa/example/.gitignore, uoa/example/make.sh, uoa/example/opp.c, uoa/uoa.c
Since some l2 switch do not support IPv4 option, or has 300pps limitation. we define an private protocol (IPPROTO_OPT), to save options like UOA. the new protocol header will be inserted between IP header and L4 header (TCP/UDP).
=> uoa/opp: use private proto for options.

src/route.c
Add netif compare to make lookup local route happy.
Issue produce:
[root@localhost bin]# ./dpip vlan add dpdk0.100 link dpdk0 id 100
[root@localhost bin]# ./dpip addr add 192.168.1.101/24 dev dpdk0.100
[root@localhost bin]# ./dpip addr add 192.168.1.101/24 dev dpdk0
[root@localhost bin]# ./dpip addr del 192.168.1.101/24 dev dpdk0.100
[root@localhost bin]# ./dpip route show
inet 192.168.1.101/32 via 0.0.0.0 src 0.0.0.0 dev dpdk0.100 mtu 1500 tos
0 scope host metric 0 proto auto
inet 192.168.1.0/24 via 0.0.0.0 src 192.168.1.101 dev dpdk0 mtu 1500 tos
0 scope link metric 0 proto auto
=> dpvs: fix a boring issue with two same ip configured.

src/common.c, src/netif.c
When I tested UOA, I found that uperf can only reach more than 4,000 sessions at a time. This is because in dpvs, RSS does not support UDP mode yet, so RSS use IP to hash. That is, all uperf traffic hits the same CPU.
=> add udp/tunnel RSS support,supplement dpvs_strerror

src/neigh.c
neighbour: use nud_timeouts instead of arp_timeout and fix bug of arp_unres_qlen parsing
=> neighbour：delete useless variable

tools/keepalived/keepalived/check/ipvswrapper.c
case: 当修改完keepalived.conf中的virtual_server_group中的ip或者port之后，reload keepalived，发现没有real_server。
=> fix bug in <case IP_VS_SO_SET_EDITDEST>

src/Makefile
Get DPVS version from git tags or commit id if no tag exists instead of maintaining the VERSION shell script.
=> version: get version from git tags or commit id if no tag exists.

src/ipvs/ip_vs_conhash.c
In the case the same real server is configured with the different udp ports for
quic packet processing, the same port is always selected and the other ports
have no chance to be selected. And the root cause is currently consistent hash
cares about only ip address.
So the solution is let consistent hash care about ip plus port instead.
=> conhash: use the real server's port along with its ip as the hash key.

tools/keepalived/keepalived/check/check_http.c, tools/keepalived/keepalived/check/check_tcp.c
1.No matter how many checks dump, it only shows the last one
2.If dump tcp and misc check, and the last one is not tcp check, may cause coredump for access null pointer.
$ sudo gdb ../dpvs/bin/keepalived /core.129771 
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-100.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/dpvs/dpvs_conhash/dpvs_dpdk/dpvs/bin/keepalived...done. …
=> fix dump check bug:

tools/ipvsadm/ipvsadm.c
在查询黑名单时，不支持icmp协议。
VIP:VPORT            PROTO    BLACKLIST           
0.0.0.0:0        UDP      172.1.1.1           
0.0.0.0:0        UDP      192.168.1.1         
0.0.0.0:0        TCP      172.1.1.1           
0.0.0.0:0        TCP      192.168.1.1         
proto not support!proto not support!
=> Add ICMP protocol for show blacklist.

tools/dpip/link.c
$ ./dpip link show
[dpvs_getsockopt] scoket msg connection error: No such file or directory
Fail to get configured NIC list: <unknow>.
Segmentation fault (core dumped)
=> fix: if dpvs process is not started, exec dpip link show will generate a coredump

tools/ipvsadm/ipvsadm.c
laddr pbuf is not long enough for ipv6
=> fix bug for laddr show

src/main.c
the return value of pthread_getaffinity_np and pthread_setaffinity_np must be set to the variable errno to describe what went wrong.
=> set errorno after pthread_get/setaffinity_np fails

src/ipvs/ip_vs_conhash.c
when rs weight is 0, node in list will not be deleted
=> fix bug for conhash:

kmod/toa/toa.c
When real server creates an IPv6 socket and listens on a port with any address, it can handle IPv4 packet. In this situation, TOA module can still retrieve client's src port. This patch fix the missing for adding client's src port to toa_ip6_data structure.
=> add missing src port in toa module

kmod/toa/toa.c
Reverts iqiyi/dpvs#391
This fix has issue. The port should be tdata.port. Please revert it first.
=> Revert "add missing src port in toa module"

kmod/toa/toa.c
When real server creates an IPv6 socket and listens on a port with any address,
it can handle IPv4 packet. In this situation, TOA module can still retrieve client's src port.
This patch fix the missing for adding client's src port to toa_ip6_data structure.
=> TOA: add missing src port in toa module

tools/keepalived/keepalived/check/ipwrapper.c
```bash
Program terminated with signal 11, Segmentation fault.
#0  0x000000000040fb72 in weigh_live_realservers (vs=vs@entry=0xca0470) at ipwrapper.c:47
47	ipwrapper.c: No such file or directory.
Missing separate debuginfos, use: debuginfo-install glibc-2.17-196.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-8.el7.x86_64 libcom_err-1.42.9-10.el7.x86_64 libgcc-4.8.5-16.el7_4.1.x86_64 libselinux-2.5-11.el7.x86_64 nss-softokn-freebl-3.28.3-8.el7_4.x86_64 numactl-libs-2.0.9-6.el7_2.x86_64 openssl-libs-1.0.2k-8.el7.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  0x000000000040fb72 in weigh_live_realservers (vs=vs@entry=0xca0470) at ipwrapper.c:47
#1  update_quorum_state (vs=vs@entry=0xca0470) at ipwrapper.c:327
#2  0x0000000000410016 in init_service_vs …
```
=> keepalived: fix crash when remove all RS(s) from virtual service group

include/dpdk.h, src/netif.c
polling定时器中仅把LACP包丢进发送队列,只有当业务层有数据时才会触发burst函数，真正将发送队列中的LACP包发送给交换机。
使能dedicated_queues，polling定时器会直接发送LACP报文。
=> enable bonding mode4 dedicated queue

src/ipv4.c, src/ipvs/ip_vs_core.c
OSPF IP fragments may get lost in 'ip4_defrag' procedure.
Considering DPVS does not process OSPF protocol, we send OSPF
packets to KNI before any inet hooks.
=> ipv4: fix OSPF IP fragmentation problem

tools/keepalived/keepalived/check/ipvswrapper.c
uint32_t inet_sockaddrip4(struct sockaddr_storage *addr)
在snat场景下，由于其返回类型为uint32_t导致其返回的ip值为0xffffffff，进而导致配置黑名单失败
=> fix bug: add bklst fail when snat mode.

Makefile, src/ipvs/ip_vs_conn.c, src/ipvs/ip_vs_redirect.c, src/netif.c
1. 修复服务器CPU数量大于或等于DPVS_MAX_LCORE时，DPVS无法启动的问题
2. 主Makefile增加distclean规则
3. 修复conn分配失败时，redirect 功能导致的 Crash 问题
4. 优化了conn redirect内存使用
=> Redirect bugfix

tools/keepalived/keepalived/vrrp/vrrp_ipaddress.c, tools/keepalived/keepalived/vrrp/vrrp_netlink.c
1. vrrp process crash when reload dpvs, this patch check NULL pointer before use strcmp.
2. if_queue is freed by free_interface_queue() when reload keepalived,
members of if_queue in old_vrrp_data should not be used. Interface index is used instead.
=> keepalived: fix vrrp process crash and static ipaddress deletion bug

src/ctrl.c
o When dpvs runs with 16 worker cores, like 'dpvs -- -l 0,1-8,11-18', we need to
larger buffer to accommodate the debugging info.
=> ctrl: increase buffer size to 8192 from 4096.

src/ipvs/ip_vs_stats.c
in most cases, this function run on master core and socket 0
=> alloc_percpu_stats: alloc memory from all sockets

kmod/toa/toa.c
fix crash problem when toa is used on centos 7.6.
=> fix crash problem when toa is used on centos 7.6

patch/dpdk-stable-17.11.2/0003-rh75-ndo_change_mtu.patch
In newer dpdk RH7.5 has been supported and i make a patch to make 17.11.2 to do the same.
Still under testing and it looks good till now.
=> Patch dpdk-17.11.2 to support rh75

src/netif.c
Opposite inner 'if' condition leads to a dead code block (outer condition is 'ii < NETIF_MAX_BOND_SLAVES' and inner condition is 'ii >= NETIF_MAX_BOND_SLAVES')
=> delete a dead code block

src/ipvs/ip_vs_conn.c
- Rename conn_expire() to dp_vs_conn_expire().
=> ipvs: refactor conn_expire() to make the code logic clear.

include/ipvs/stats.h, src/ipvs/ip_vs_dest.c, src/ipvs/ip_vs_service.c, src/ipvs/ip_vs_stats.c
- Keep conformity of the same function name style, module_name_verb() like
dp_vs_conn_get().
- Remove dp_vs_copy_stats() that has no definition.
=> ipvs: rename dp_vs_add_stats() to dp_vs_stats_add().

include/ipvs/conn.h, include/timer.h
Without this patch,
```
/tmp/dpvs/src//../include/timer.h:54:13: error: inline function ‘ticks_to_timeval’ declared but never defined [-Werror]
inline void ticks_to_timeval(const dpvs_tick_t ticks, struct timeval *tv);
^~~~~~~~~~~~~~~~
/tmp/dpvs/src//../include/timer.h:53:20: error: inline function ‘timeval_to_ticks’ declared but never defined [-Werror]
inline dpvs_tick_t timeval_to_ticks(const struct timeval *tv);
^~~~~~~~~~~~~~~~
In file included from /tmp/dpvs/src//../include/inetaddr.h:25:0,
from /tmp/dpvs/src//../include/netif.h:23,
from /tmp/dpvs/src/ipv4_frag.c:23:
/tmp/dpvs/src//../include/timer.h:54:13: error: inline function ‘ticks_to_timeval’ declared but never defined [-Werror]
inline void ticks_to_timeval(const dpvs_tick_t ticks, struct timeval *tv);
^~~~~~~~~~~~~~~~ …
```
=> Fix compile error caused by inline method.

src/netif.c, src/scheduler.c
- Currently, the crash is met caused by the below assertion when dpvs runs
with "-- -l 0,1-8,11-18".
assert(g_lcore_role[cid] == LCORE_ROLE_IDLE) within lcore_role_init().
Without the fix, g_lcore_role[17] is LCORE_ROLE_MAX so dpvs crashes.
=> netif: allow to use the non-continuous lcores, like "-l 0,1-8,11-18".

tools/keepalived/keepalived/check/ipvswrapper.c
1.add laddr style:
local_address_group laddr_g1 {
10.220.172.10-253 dpdk0
}
2. error log info:
IPVS: dp_vs_laddr_bind: [04] no lip/lport available !!
3.reason:
vport is not assigned when add laddr, cause vs and laddr association failure
=> fix: add laddr by range style.

include/global_data.h, src/global_data.c, src/ipvs/ip_vs_laddr.c, src/ipvs/ip_vs_service.c, src/netif.c
dpvs will be crashed when ipvsadm -ln --cpu M while max cpu cnt = N(M>=N).
=> dpvs: fix problem that dpvs crash when cpu id is larger than cpu cnt.

src/ipvs/ip_vs_laddr.c
dpvs return the error log "SERVICE: laddr_sockopt_get: find no laddr for cid=2" in the function laddr_sockopt_get because of the different cid  when executing ipvsadm -G --cpu N (N > 0, which is the cpu index of a slave worker).
=> dpvs: fix the problem of  showing the laddr info of  a slave worker

src/ipvs/ip_vs_blklst.c
dpvs: fix the dpvs msg memory leak in dp_vs_blklst_del
=> dpvs: fix the dpvs msg memory leak

src/ctrl.c
1. log info: "dpvs: MSGMGR: msg_type_table_print: buffer not enough"
=> fix: mt_lock's read lock not released.

src/iftraf.c, src/ipset.c, src/ipv6/route6_hlist.c, src/ipv6/route6_lpm.c, src/ipvs/ip_vs_blklst.c, src/ipvs/ip_vs_conn.c, src/ipvs/ip_vs_laddr.c, src/ipvs/ip_vs_redirect.c, src/route.c
dpvs:fix the error of no memory by allocing memory without specific numa.
eg:  
we use the funciton rte_zmalloc without specific numa to add a ipv4 route in the function route_sockopt_set, while using the function  rte_calloc_socket to alloc memory in the function route_sockopt_get, which maybe casue the no memory error.
so use rte_malloc instand of rte_malloc_socket,  rte_zmalloc instand of rte_zmalloc_socket, rte_calloc instand of rte_calloc_socket.
=> dpvs:fix the error of no memory by allocing memory without specific numa

src/inetaddr.c, src/ipvs/ip_vs_blklst.c
1) fix the bug of blklst multicast msg send fail
configure multi blklst ip in keepalived.conf, only the first ip is configured successfully, the other blklst ip is configured failed because of the repeated sequence number in the function multicast_msg_send  when master send multicast msg to slave worker.
ps:  the error log as below
May 19 10:19:05 dpvs[32671]: MSGMGR: multicast_msg_send:msg@0x7f771710548c, repeated sequence number for multicast msg: type 9, seq 0
May 19 10:19:05 dpvs[32671]: SERVICE: [dp_vs_blklst_add] fail to send multicast message
2) adjust  format (void*)  to (void  *)
=> fix the bug that blklst configuration multicast msg send fail

src/scheduler.c
Use per lcore variable instead of a global array. The origin global array has cache false sharing issue,
and it is in critical datapath. Use per lcore variable to fix this issue.
According to my personal simple testing, it can improve about 8% pps for syn flood traffic.
=> scheduler: a performance optimization

conf/dpvs.conf.items, include/netif.h, src/netif.c, src/sa_pool.c
o By default, fdir filter is always enabled.
```
netif_defs {
...
<init> device dpdk0 {
fdir {
...
<init> filter  on
}
}
...
}
```
o In some case that dpvs is deployed in some VM, VM does not support fdir filter
configuration so only ONE single worker core can be used accordingly. In fact,
we don't need to add fdir filters, but create only the specific sa pools.
With "packet redirect" enabled, multiple worker cores can be used accordingly
for the benefit of performance, like cps/pps.
```
netif_defs {
...
<init> device dpdk0 {
fdir {
filter  off
}
}
...
}
ipvs_defs {
conn {
redirect  on
}
}
```
=> fdir: add "filter" switch of fdir config to support multi-core processing in VM

include/conf/eal_mem.h, include/eal_mem.h, src/eal_mem.c, src/main.c, tools/dpip/Makefile, tools/dpip/dpip.c, tools/dpip/eal_mem.c
Currently there is no effective tool to check dpdk memory usage; the commit is used to display dpdk memory usage;
The method of use is as follows：
$dpip eal-mem help
Usage:
dpip eal-mem show [seg | ring | zone | pool]
=> dpip: show dpdk mem info

include/ipvs/sched.h, src/ipvs/ip_vs_conhash.c, src/ipvs/ip_vs_sched.c, src/ipvs/ip_vs_wrr.c
the memory will be a big problem with the conhash scheduling for vs when large count of vs and rs configured per lcore.
=> conhash: use weight ratio to reduce virtual node num in rbtree

include/conf/common.h, include/conf/netif.h, include/dpdk.h
- Both conf/netif.h and include/dpdk.h define the same below types.
a) lcoreid_t
b) portid_t
c) queueid_t
Move the above types to the same header file, conf/common.h instead of
definiting them in two header files.
=> conf: move the types of portid_t and queueid_t to conf/common.h.

src/inetaddr.c
- `ifa_entry_mod` function invoked by all core,  need correct `is_global` parameter for  `dpvs_time_now`  function.
- `dad_timer` will sched twice when add a ipv6 ifa address and update it immediatly.
=> Fix mod ifa bug.

include/inetaddr.h, src/inetaddr.c, src/netif.c
Need invoke `idev_add_mcast_init` in all lcore, otherwise lcore cannot handle ICMP6 neighbor advertisement packet which ipv6 dst is `ff02::1` or `ff02::2`. Because in `ip6_mc_local_in` function it will invoke `inet_chk_mcast_addr` to check ipv6 dst and it will failed, so the packet will deliver to KNI.
=> fix per lcore need mcast init

include/sa_pool.h, src/inetaddr.c, src/sa_pool.c
**BUG Scenario:** 
We use DPVS for nat64,  BUG stable reproduction steps:
1. Add local ip
2. Make some packet, such as udp traffic.
3. Delete local ip
4. Loop the above steps
5. Repeat the cycle sveral times, and then traffic disconnected
And  `dpip addr show -v`  show that miss some ifa in lcore:
- We use 4 local ip:  192.168.202.110, 192.168.202.109, 192.168.202.108, 192.168.202.107
- Master core: 2; slave lcore: 3,4,5,6
- When traffic disconnected, `dpip addr show -v` show that slave lcore miss ifa, which make nat64 failed.
- Master core had all ifa.
```
~# dpvsadm --get-laddr
VIP:VPORT            TOTAL    SNAT_IP              CONFLICTS  CONNS
[::]:0               4
192.168.202.106      0          0
192.168.202.105      0          0
192.168.202.104      0          0
192.168.202.103 …
```
=> Reuse expired ifa during adding ifa.

include/sa_pool.h, src/sa_pool.c
Each sa_entry_pool has a huge sa_entry array, which waste too much memory.
=> Optimized sa_entry memory.

tools/keepalived/keepalived/check/libipvs.c
If the hash factor of the conhash scheduling algorithm of vs is sip, we want to change the hash factor to qid through ipvsadm -E -u xxx -s conhash -Y qid. we will find that the vs will have two hash factors, sip and qid through ipvsadm -ln.
=> ipvsadm: fix change conhash target error

tools/keepalived/keepalived/include/check_data.h, tools/keepalived/keepalived/include/ip_vs.h
In kernel 4.1 and above, the macro WITH_LVS_64BIT_STATS will be defined in config.h.
The function ipvs_get_services is in libipvs.c which includes config.h, so the member stats in struct ip_vs_service_entry_app will be the type of struct ip_vs_stats64.
While the function list_all is in ipvsadm.c which does not include config.h, so the member stats will be the type of struct ip_vs_stats_user.
The different size of member stats in struct ip_vs_service_entry_app will affect the value of member af and nf_affr in struct ip_vs_service_entry_app.
=> ipvsadm: fix ipvsadm -ln show null error

src/ipvs/ip_vs_dest.c, src/ipvs/ip_vs_service.c, tools/keepalived/keepalived/check/ipwrapper.c, tools/keepalived/keepalived/include/check_data.h
Two questions:
1) the max_conn of  dest should be based on the whole machine, not based on the lcore;
2) Changing the uthreshold of rs in keepalived.conf does not take effect;
=> fix the dest max conn bug

kmod/toa/toa.c
#484 by @goecho was trying to fix crash problem on some kernel versions. The new function is_ro_addr() is used to check the `address` is `ro` or `rw`.
but the condition seems weired:
```
if (pte->pte &~ _PAGE_RW) {
ro_enable = 1;
}
```
`pte->pte &~ _PAGE_RW` means there are some other flags being set, no matter RW flags is set or not.
=> kmod/toa: fix is_ro_addr()

src/ipvs/ip_vs_proto_tcp.c
(1): The connection only have one data to send.
(2): The data packet carry the fin flag.
when a connection satisfies the two conditions, it will can't add the toa option to the packet, then the RS will can't get the client IP. 
The original code：(in function tcp_fnat_in_handler)
/* add toa to first data packet */
if (ntohl(th->ack_seq) == conn->fnat_seq.fdata_seq
&& !th->syn && !th->rst /*&& !th->fin*/)
tcp_in_add_toa(conn, mbuf, th);
We should delete the check for th->fin.
This problem has been dicussed in the WeChat group named "DPVS dicussion group", then we also discussed that the toa option added in the tcp syn packet will not be used in the RS.
In production environment，I has captured the tcp stream which satisfies the two conditions, and than the nginx in RS can't get the clientip. …
=> Sometimes RS can't get client ip

tools/keepalived/lib/scheduler.c
**Describe the bug**
keepalived running too long，which lead to print “scheduler：epoll_wait error ：invalid argument”
**To Reproduce**
add same vs or rs to keepalived.conf
systemctl start keepalived
wait some time。
gdb att checker process.
watch master-> epoll_count
**Expected behavior**
when keepalived.conf is not changed, the epoll_count is not increased。
under a lot of checkers, donot print "scheduler：epoll_wait error ：invalid argument" （because epoll_count is reversed）
see: https://github.com/acassen/keepalived/issues/1631
=> keepalived: fix epoll_wait return err

include/pdump.h, src/main.c, src/pdump.c
Fix pdump initialization problem introduced by pr #674.
Pdump should be initialized after cfgfile module, or `g_dpvs_pdump` is not set before used.
=> pdump: fix pdump initialization problem introduced by pr #674

src/ipv4.c
when `fl4->fl4_saddr.s_addr == htonl(INADDR_ANY) ` ,source ip should be selected after route lookup.
=> show dpvs's ip in traceroute path

include/ipv4.h
If UOA mode is set to `ipo` (use IP option) and UDP checksum offloading is disabled, the UDP checksum generated by DPVS is not correct.
For DPDK newer than 17.11.10, implementation for `rte_ipv4_udptcp_cksum()` has changed, where `l4_len` depends on both `ipv4_hdr->total_length` and `(ipv4_hdr->version_ihl & 0xf)`:
```
static inline uint16_t
rte_ipv4_udptcp_cksum(const struct ipv4_hdr *ipv4_hdr, const void *l4_hdr)
{
// ...
l3_len = rte_be_to_cpu_16(ipv4_hdr->total_length);
l4_len = l3_len - (ipv4_hdr->version_ihl & 0xf) * 4;
if (l4_len < 0)
return 0;
// ...
}
```
Thus, we need to mock both `iph->total_length` and `iph->version_ihl` before passing packet data to `rte_ipv4_udptcp_cksum()`.
=> fix: UDP checksum not correct using ipo UOA with checksum offloading disabled

src/ctrl.c
Signed-off-by: linjianying <linjianying.dev@gmail.com>
=> fix dpvs_sockopts sockoptid_t register duplicated in sockopts_exist

src/timer.c
dpvs-timer: now implement has a Implied limitation that will cause crash, optimize it
=> optimize a timer limitation that cause crash in our project, we test it and work well online for 3 months

include/ipvs/conn.h
Reduce memory usage when CONFIG_DPVS_IPVS_STATS_DEBUG is not defined.
=> conn: reduce memory usage of dp_vs_conn

src/ipvs/ip_vs_conhash.c
It may affect the weight ratio of other rs when adding/modifying/deleting rs.
For example, rs1(weight 3, weight_ratio 1)  rs2(weight 6, weight_ratio 2) existed in svc1,  now we add rs3(weight 4); we will calculate new gcd, gcd(3,6,4)=1, so set weight_ratio of rs3 is 4/1 =4;  But the weight ratio of rs1 and rs2 DO NOT updated in the tree.
=> bugfix: unreasonable conhash weight ratio while updating rs

src/netif.c
[root@localhost pdump]# dpdk-pdump -- --pdump 'device_id=net_bonding0,queue=*,rx-dev=/root/pdump/pcap
/capture.pcap,tx-dev=/root/pdump/pcap/capture.pcap'
EAL: Detected 32 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket_157010_2fd9063deca7c
EAL: Probing VFIO support...
EAL: PCI device 0000:5e:00.0 on NUMA socket 0
EAL:   probe driver: 8086:1572 net_i40e
EAL: PCI device 0000:5e:00.1 on NUMA socket 0
EAL:   probe driver: 8086:1572 net_i40e
Device 0000:5e:00.1 is not driven by the primary process
EAL: secondary process attach failed, ethdev doesn't existEAL: Requested device 0000:5e:00.1 cannot be used
EAL: PCI device 0000:61:00.0 on NUMA socket 0
EAL:   probe driver: 8086:37d0 net_i40e
Device 0000:61:00.0 is not driven by the primary process
EAL: …
=> bugfix: dpdk-pdump can't use 'device_id=net_bondingX'

src/ipvs/ip_vs_core.c, src/ipvs/ip_vs_xmit.c
tunnel模式下，报文添加外层ip头，长度超过mtu后，返回的icm包里mtu值应该减去外层ip头长度。
icmp6的构造传入参数应该是主机序列的，因为icmp6_send函数里面对传入的参数mtu做了大端转换。
=> modify bug: icmp6 mtu error, tunnel mode icmp/icmp6 error

tools/ipvsadm/ipvsadm.c, tools/keepalived/keepalived/check/libipvs.c
example：
ipvsadm -ln -H "snat-svc"
ipvsadm -E -H "snat-svc"
=> modify bug: SNAT mode, ipvsadm displaying and editing the SVC will fail.

kmod/uoa/example/udp_serv.c, kmod/uoa/uoa.c
The patch fixed the following problems.
1. In opp mode, after uoa data parsed, the opp header and data are translated to ipv4 header NOOP options, where the memory of packets is not dealt with correctly.
2. Some container network enforcements may hinder the host from passing to container the packets with uoa private protocol data, that is ip protocol 254. Thus add an optional param to uoa to parse uoa data at the tail of netfilter forwarding chain.  Though it's not  a thorough solution due to the complixity and diversity of container networking enforcements, we verified that it does work with k8s cilium cni deployed without encapsultion.
=> Uoa in container

tools/keepalived/lib/notify.c
getpgid may return -1 or 0;
reutrn -1: kill(1, SIGTERM), send signal TERM to systemd.
return 0: kill(0, SIGTERM), send signal to keepalived master and keepalive checker, which cause keepalive exit.
(1) getpgid 
pid_t getpgid(pid_t pid);
getpgid(),  return a process group on success. 
On error, -1 is returned, and errno is set appropriately.
return 0 for parameter pid specify a kernel process.
(2) kill
int kill(pid_t pid, int sig);
DESCRIPTION:
If pid equals 0, then sig is sent to every process in the process group of the calling process.
(3)Steps to reproduce
3.1> Configure a large number of rs that use misc for health check
3.2> while true; do  kill -HUP `cat /var/run/keepalived.pid`; sleep 20; done
Note: 
In order to increase the probability of conflict between the pid of the kernel …
=> keepalived: fix keepalived exiting while reloading

src/ipvs/ip_vs_proto_udp.c
In fullnat64 mode, uh(udp header) will be wrong by iphdrlen offset which is from ip4_hdrlen(mbuf), which will cause wrong client source port for uoa.
=> fix uoa client sport error in fnat64

conf/dpvs.conf.items, conf/dpvs.conf.sample, conf/dpvs.conf.single-bond.sample, conf/dpvs.conf.single-nic.sample, src/ipvs/ip_vs_synproxy.c
Tcp reciece window of the client is closed in the first step of synproxy,
and client could only send window probe ack packets without payload in the
case. So it conflicts with the defer_rs_syn, which schedules ipvs connection
only when tcp ack packets with payload catched in the second step of synproxy.
Besides, a config item close_client_window is added to disable client window
close in the first step of synproxy.
Signed-off-by: ywc689 <ywc689@163.com>
=> synproxy: fix fullnat tcp forwarding problem when defer_rs_syn enabled

include/netif.h, src/kni.c, src/netif.c
The size of kni_mbuf_pool is 65535. DPDK KNI may be starvation when mbufs are exhausted. Many reasons cause the mbufs of the kni_mbuf_pool to be cached, such as kni_rx_ring_*, driver.
For example, under the configuration of 16 txqs + 4096 descriptors, since ixgbe uses lazy recycling, a maximum of 65536 mbufs will be cached.
Using a large enough mbuf pool is an easy fix. pktmbuf_pool is the best choice.
DPDK KNI starvation bug detail:
http://patches.dpdk.org/project/dpdk/patch/20221109060434.2012064-1-zhouyates@gmail.com/ http://patches.dpdk.org/project/dpdk/patch/20221230042338.1670768-1-zhouyates@gmail.com/
=> kni: fix possible alloc_q starvation

src/ipvs/ip_vs_proto_udp.c
Length of ipo is sizeof(struct ipopt_uoa) + IPv4_addr_length = 8.
=> dpvs: fix ipo option length bug when insert ipo.

src/parser.c, tools/ipvsadm/ipvsadm.c
1. dpvs: fix cfgfile parser malloc problem
2. ipvsadm: fix icmpv6 option and improve help message
=> fix cfgfile parser malloc problem and ipvsadm improvement

src/ipvs/ip_vs_core.c, tools/dpvs-agent/cmd/ipvs/post_vs_vip_port_rs.go, tools/dpvs-agent/cmd/ipvs/put_vs_vip_port_rs.go, tools/healthcheck/pkg/helthcheck/http_checker.go, tools/healthcheck/pkg/helthcheck/http_checker_test.go, tools/healthcheck/pkg/helthcheck/server.go, tools/healthcheck/pkg/helthcheck/udp_checker.go, tools/healthcheck/pkg/helthcheck/udp_ping_checker.go, tools/healthcheck/pkg/helthcheck/udp_ping_checker_test.go, tools/healthcheck/pkg/lb/types.go
* Add healthcheck method 'udpping' and make it the default checker for UDP targets.
The 'udpping' checker first checks the l3 network connectivity with ping checker, and performs udp checker only ping checker responds ok. It's an enhancement for the simple udp checker when udp port probe times out.
* Add healthcheck method 'http' for HTTP/HTTPS targets.
=> healthcheck: more checker methods and bugfix

src/ipv4.c
ip4_idents is global and can be used by all threads. rte_atomic32_read first and then rte_atomic32_add are not atomic operations.
=> ip4_select_id use rte_atomic32_add_return

src/ipvs/ip_vs_proto_tcp.c
But sometimes, the backend dpvs system allows toa data filled by the previous dpvs system.
=> Remove toa field, fix security vulnerability.

patch/dcdn-toa.patch, src/ipvs/ip_vs_proto_tcp.c
1. Do not insert toa data in syn packets any more.
2. Compact tcp option space or remove some options when inserting toa data failed  and then try again.
3. Emit a warning log for audit when toa insertion failed finally.
=> ipvs: toa enhancements

src/ipvs/ip_vs_synproxy.c
=> use better random source

tools/keepalived/keepalived/check/ipwrapper.c
keepalived new_vs quorum_state_up always be true and quorum_up script will not be excuted when all old rs(healthcheck is alive) are removed and new rs(healthcheck is alive) add in same reload.
=> bugfix: new_vs quorum_up script will not be excuted

tools/keepalived/keepalived/check/libipvs.c
在使用
`ipvsadm --del-laddr -z 192.168.1.2 -t 10.1.1.11:80 -F dpdk1`
命令删除LIP时报错：
> MSGMGR: [sockopt_msg_send:msg#SOCKOPT_SET_LADDR_DEL] errcode set in sockopt msg reply: no service
发现ipvsadm代码中参数有误，修改后可以正常删除LIP
=> tools/ipvsadm: fix could not remove lip

.github/workflows/build.yaml, .github/workflows/run.yaml
This is a temporary fix, and hopefully can work until Spring 2025. https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
=> ci: fix unsupported Node20 problem

conf/dpvs.conf.items, include/conf/inetaddr.h, include/ctrl.h, include/inetaddr.h, include/ip_tunnel.h, include/ipv6.h, include/linux_ipv6.h, include/netif.h, src/inetaddr.c, src/ip_gre.c, src/ip_tunnel.c, src/ipip.c, src/ipset/ipset_core.c, src/ipv6/ipv6.c, src/ipv6/route6.c, src/ipvs/ip_vs_blklst.c, src/ipvs/ip_vs_conn.c, src/ipvs/ip_vs_whtlst.c, src/netif.c, src/route.c, src/scheduler.c, src/timer.c, src/vlan.c
1. Fix segmentation fault problem when running on machines whose cpu number is over DPVS_MAX_LCORE(issue #991).
2. Refactor netif_rte_port_alloc with netif_alloc.
3. Fix prolems in IPv6 all-nodes and all-routers address initialization.
4. Support IPv6 link-local address auto configuration(refer to linux:[addr_gen_mode](https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt)).
=> Bugfix 20240902

src/netif.c
补丁修复了下列情况的数据包被误统计为dropped的问题：
- 某个转发核收到arp reply后广播到其他转发核的数据包
- 标记NETIF_PORT_FLAG_FORWARD2KNI的port的数据包又被判断为EDPVS_KNICONTINUE
上述场景不再累计dropped计数
=> netif: fix duplicate ARP replies or KNI packets being counted as dropped

conf/dpvs.bond.conf.sample, conf/dpvs.conf.items, conf/dpvs.conf.sample, conf/dpvs.conf.single-bond.sample, conf/dpvs.conf.single-nic.sample
修正了一些未标记为<init>的配置项和误标记为<init>的配置项。
删除了无意义的注释。
=> conf: optimize init attribute

kmod/toa/toa.c
the memory for  `toa_ip6_sk_lock.lock`  is allocated only after it is referenced in the `for_each_possible_cpu` loop.  While this does not cause any obvious crashes or errors on Ubuntu, it is still an incorrect usage.
=> toa: fixed #1012 allocating 'toa_ip6_sk_lock.lock' before using it
