iqiyi/dpvs

README.md

1. README.md: update test env description (e.g., NUMA, ...), change prompt.
2. fix keepalived build issue by adding keepalived/bin dir.

update README.md and fix keepalived build issue.

---

src/ip_vs_laddr.c

```bash
./ipvsadm -G
```
the `CONNS` field is always 0

support to get connection count for local address

---

README.md

README.md: fix typo.

---

doc/tutorial.md

The prefix length of `kni_host` route must be 32.

doc: tutorial.md: plen of kni_host route must be 32

---

README.md
doc/TODO.md
doc/tutorial.md

Update README for new DPDK version `DPDK-17.05.2`.

README.md: update for DPDK-17.05.2

---

scripts/config_snat_sample.sh
src/ipvs/ip_vs_conn.c

Just a config script example of SNAT mode.  You can modify it easily for your environment.
Its config area looks like:
\#\#\#\#\# Basic configurations \#\#\#\#\#
\#\#\#\#\# NOTE: modify these according to your environment \#\#\#\#\#
WAN_IP_LIST=('192.168.10.2' '192.168.10.4' '192.168.10.5' '192.168.10.6')
WAN_PREF=24             # WAN side network prefix length.
GATEWAY=192.168.10.3    # WAN side gateway
LAN_IP=172.16.10.2
LAN_PREF=24
SRC_RANGE='172.16.0.0-172.16.254.254'
WAN_DEV=dpdk1 # device for WAN IP list to bind on
LAN_DEV=dpdk0 # device for LAN IP to bind on
PROTOCOLS=('tcp' 'udp' 'icmp')
DPVS_TOOL_PATH="."
DPIP_CMD="$DPVS_TOOL_PATH/dpip "
IPVSADM_CMD="$DPVS_TOOL_PATH/ipvsadm "
It runs like this:
\# sh ./config_snat.sh -s all
====Add IP Address to devices====
./dpip  addr add …

Add a config script for SNAT mode

---

README.md
tools/ipvsadm/ipvsadm.c

readme: add more build dependencies.

---

README.md
include/ipvs/proto_icmp.h
scripts/config_snat_sample.sh
src/ipvs/ip_vs_conn.c
src/ipvs/ip_vs_proto_icmp.c
tools/ipvsadm/ipvsadm.c

Fix email.

---

scripts/config_fullnat_2arm_sample.sh
scripts/config_snat_sample.sh

Add a fullnat configure script sample.
Fix check_default_gw() function in snat's configure script sample.

Add a fullnat configure script sample.

---

scripts/config_fullnat_2arm_sample.sh

Add synproxy enable/disable to scripts/config_fullnat_2arm_sample.sh

---

doc/tutorial.md
src/ipvs/ip_vs_core.c
src/ipvs/ip_vs_xmit.c

1. doc: tutorial: fix dpdk version.
2. ipvs: support TTL check and decrease.

Fix dpdk version in doc and add TTL check/decriease for SNAT/FNAT.

---

tools/keepalived/keepalived/check/check_tcp.c

reload keepalived with add/delete real servers, it might crashed here.

fix a seg fault in free_tcp_check()

---

src/pidfile.c

Fix a fd leak in dpvs_running()

---

src/neigh.c

pkt malloc in mempool of neighbour module will not release until mempool in netif is not enough.
So, just use one mempool in dpvs.

fix bug: send arp fail.

---

src/ipv4.c
src/ipvs/ip_vs_core.c

add "conn->dest->fwdmode != DPVS_FWD_MODE_SNAT" judge in function
xmit_inbound_icmp and xmit_outbound_icmp for traceroute debug.

ipvs: core: xmit ICMP for SNAT.

---

src/netif.c

fix a little usage error of bond_cfg->slaves

---

src/ipvs/ip_vs_xmit.c
src/netif.c
src/sa_pool.c
src/tc/sch_tbf.c

remove some redundant pieces of code.

---

src/main.c

make it possibe to get version info during runtime.

version: make it possibe to get version info during runtime

---

doc/faq.md
include/conf/ipv6.h
include/ctrl.h
include/flow.h
include/icmp6.h
include/inet.h
include/ipv4.h
include/ipv6.h
include/linux_ipv6.h
include/route.h
include/route6.h
src/Makefile
src/cfgfile.c
src/icmp.c
src/inet.c
src/ip_tunnel.c
src/ipv4.c
src/ipv6/icmp6.c
src/ipv6/ipv6.c
src/ipv6/ipv6_ctrl.c
src/ipv6/ipv6_exthdrs.c
src/ipv6/route6.c
src/ipvs/ip_vs_core.c
src/ipvs/ip_vs_proto_tcp.c
src/ipvs/ip_vs_rr.c
src/ipvs/ip_vs_wlc.c
src/ipvs/ip_vs_wrr.c
src/ipvs/ip_vs_xmit.c
src/route.c
src/sa_pool.c

* add IPv6 layer codes.
- IPv6 codes (ipv6, flow/route, ...)
- adjust inet and related ipv4/route codes to support IPv6.
* add route6/icmpv6 stub functions for test.

ipv6: basic protocol support.

---

include/inet.h
include/linux_ipv6.h
src/ipv6/icmp6.c
src/ipv6/ipv6.c
src/ipv6/ipv6_ctrl.c
src/ipv6/ipv6_exthdrs.c
src/ipv6/route6.c
tools/dpip/Makefile
tools/dpip/dpip.c
tools/dpip/ipv6.c

* `dpip` tool to fetch IPv6 statistics.
* support multicast input.
* more stub codes for testing including forwarding/multicast

IPv6 basic protocol continued.

---

src/ipv6/icmp6.c

Fix icmp6 checksum with ext-header.

ipv6/icmp6: fix icmp6 csum with ext-hdr

---

include/conf/neigh.h
include/icmp6.h
include/inetaddr.h
include/linux_ipv6.h
include/ndisc.h
include/neigh.h
include/netif.h
include/route6.h
src/inet.c
src/inetaddr.c
src/ipv4.c
src/ipv6/icmp6.c
src/ipv6/ipv6.c
src/ipv6/ndisc.c
src/ipv6/route6.c
src/ipvs/ip_vs_proto_tcp.c
src/ipvs/ip_vs_proto_udp.c
src/ipvs/ip_vs_xmit.c
src/main.c
src/neigh.c
src/netif.c

neighbour discovery support

---

src/ipvs/ip_vs_conhash.c

Fix: a pointer might be Null in node_fini()

---

tools/keepalived/keepalived/libipvs-2.6/dp_vs.h
tools/keepalived/keepalived/libipvs-2.6/libipvs.c
tools/keepalived/keepalived/libipvs-2.6/libipvs.h
tools/keepalived/keepalived/vrrp/vrrp_ipaddress.c
tools/keepalived/keepalived/vrrp/vrrp_iproute.c

VIP/RS/LADDR/VRRP and healthy check already be test with two stack.

keepalived support ipv6

---

conf/dpvs.bond.conf.sample
conf/dpvs.conf.items
conf/dpvs.conf.sample
conf/dpvs.conf.single-bond.sample
conf/dpvs.conf.single-nic.sample
include/ipv6.h
include/netif.h
include/route6.h
include/uoa.h
src/ipv6/ipv6.c
src/ipv6/route6.c
src/ipvs/ip_vs_proto_udp.c
src/netif.c
src/sa_pool.c
uoa/example/opp.c
uoa/example/udp_serv.c
uoa/example/uperf.c
uoa/uoa.c

Revert "Ipv6"

---

include/icmp6.h
include/inet.h
include/ipvs/service.h
include/route6.h
src/ipv6/icmp6.c
src/ipv6/ipv6.c
src/ipv6/route6.c
src/ipv6/route6_hlist.c
src/ipv6/route6_lpm.c
src/ipvs/ip_vs_conhash.c
src/ipvs/ip_vs_core.c
src/ipvs/ip_vs_proto.c
src/ipvs/ip_vs_proto_icmp.c
src/ipvs/ip_vs_service.c
src/netif.c
tools/ipvsadm/ipvsadm.c
tools/keepalived/keepalived/check/check_parser.c

OSPF SNAT ipv6 enable and bug fix 

---

src/ipvs/ip_vs_xmit.c

修复nat in out回调判断语句

---

include/ipvs/synproxy.h
src/ipvs/ip_vs_core.c
src/ipvs/ip_vs_synproxy.c

In case of it consumes too many mbufs if RS response is slow.

syn proxy: added window size close and update

---

include/ipvs/synproxy.h
src/ipvs/ip_vs_core.c
src/ipvs/ip_vs_proto_tcp.c
src/ipvs/ip_vs_proto_udp.c
src/ipvs/ip_vs_synproxy.c
src/ipvs/ip_vs_xmit.c

1,Nat64 support syn_proxy
2,some bug fix

Nat64 support syn_proxy

---

src/ipvs/ip_vs_service.c

1.fix memory leak when getting serivce which not exsits
2.fix service refcnt incorrect when getting serivce failed

1.fix memory leak when getting serivce  which not exsits 2.fix service refcnt incorrect when getting serivce failed

---

kmod/toa/example_nat64/nginx/README.md
src/inetaddr.c
src/route.c
tools/keepalived/keepalived/check/check_daemon.c
tools/keepalived/keepalived/vrrp/vrrp_daemon.c
tools/keepalived/keepalived/vrrp/vrrp_ipaddress.c
tools/keepalived/lib/parser.c

1,fix bug for all svc deleted
2,fix bug for vip/addr add failed

keepalived bug fix

---

src/ipvs/ip_vs_dest.c
src/ipvs/ip_vs_service.c

fix memory leak if handle multicast msg timeout

fix msg memory leak

---

src/ipv6/ndisc.c

During nat64 test, the below issue is met on IPv6-side (aka wan side).
Provided that dpvs's gateway IPv6 address is  fcbd:dc00:46::1.
1) When the outgoing packet destined to IPv6 client is sent out from dpvs, we
need to resolve dpvs's gateway mac address. So the below neighbour
solicitation is sent from dpvs to its IPv6 gateway.
(:: -> ff02::1:ff00:1) that includes info, "Neighbour Solicitation for
fcbd:dc00:46::1".
And the related neighbour entry, E1, is created on core A.
E1: (fcbd:dc00:46::1, 00:00:00:00:00:00, dpdk1, DPVS_NUD_S_SEND)
2) The coresponding neighbour advertisement is received on core B.
(fe80:274:9cff:fe0e:1441 -> ff02::1) that includes info, "Neighbour
Advertisement fcbd:dc00:46::1 (rtr, ovr) is at 00:74:9c:0e:14:41".
Also within ndisc_recv_na(), target address, …

ndisc/neigh: sync the neighbour entry to other cores once it is created.

---

src/ipv4_frag.c

mismatch of rte_lcore_id and rte_socket_id

mismatch of rte_lcore_id and rte_socket_id

---

src/inet.c
src/ipvs/ip_vs_nat64.c

1,delete useless lock
2,don't use memset

performance update

---

src/neigh.c

o Remove the queue length check of the newly created neighbour entry as well.

neigh: show the concrete neighbour entry info when its queue is full.

---

tools/keepalived/keepalived/check/ipvswrapper.c

fix unmatched brace.

---

src/ipvs/libconhash/util_rbtree.c

Delete useless if condition.

---

.gitignore
src/ipset.c
tools/Makefile
tools/ipvsadm/ipvsadm.c
tools/keepalived/install-sh

fix formatting and debug problem after keepalived update

fix format and build problem of new keepalived version

---

include/conf/iftraf.h
include/iftraf.h
src/sa_pool.c
tools/dpip/iftraf.c

- Remove double semicolon from sa_pool.c.

ipvs: remove ^M from the files.

---

include/ipvs/dest.h
src/ipvs/ip_vs_conn.c
src/ipvs/ip_vs_dest.c
src/ipvs/ip_vs_fo.c
src/ipvs/ip_vs_stats.c

functions as well.
- dp_vs_dest_set_avail()
- dp_vs_dest_clear_avail()

ipvs: use dp_vs_dest_is_avail() for external usage and add the below two

---

src/log.c

Array 'm[12]' accessed at index 12, which is out of bounds. After fixed, I run it with a simple local test, and it worked.

fix the array boundary overflow issue.

---

src/VERSION
src/iftraf.c

iftraf: fix misleading-indentation problem

---

tools/keepalived/keepalived/vrrp/vrrp_iproute.c

fix keepalived static route reload issue

Correct ret value of netlink_route

---

patch/dpdk-stable-17.11.2/0003-pdump-support-filter.patch

Co-authored-by: mscbg <wangqing_mscbg@163.com>

pdump filter by  five tuple.

---

patch/dpdk-stable-18.11.2/0004-rm-rte_experimental-attribute-of-rte_memseg_walk.patch
src/eal_mem.c

fix the compiling error with dpdk 18.11

fix the compiling error with dpdk 18.11

---

include/ipvs/conn.h
include/ipvs/service.h
src/ipvs/ip_vs_conn.c
src/ipvs/ip_vs_core.c
tools/ipvsadm/ipvsadm.c

One Packet Scheduler for UDP

---

conf/dpvs.bond.conf.sample
conf/dpvs.conf.items
conf/dpvs.conf.sample
conf/dpvs.conf.single-bond.sample
conf/dpvs.conf.single-nic.sample
include/conf/netif.h
include/global_data.h
include/netif.h
src/ipset.c
src/ipvs/ip_vs_conn.c
src/ipvs/ip_vs_redirect.c
src/ipvs/ip_vs_synproxy.c
src/ipvs/ip_vs_xmit.c
src/kni.c
src/neigh.c
src/netif.c
src/scheduler.c
src/tc/sch_generic.c
src/vlan.c
tools/dpip/link.c

KNI Worker Isolation.
Based on PR #601

KNI Worker Isolation (based on PR #601)

---

src/Makefile
src/dpdk.mk

Fix  not working problem introduced by commit 28d97b7(pr #667).
The problem is found by @legend050709, who provide another fix in pr #676.

bugfix: fix  not working problem introduced by commit 28d97b7(pr#667)

---

src/ipvs/ip_vs_synproxy.c

Follow-up on #602 :
* Done refactor to keep the code tidy
* Fix: wrong TCP sequence number and possible wrong checksum

feature: send TCP RST if syn cookie check fails

---

doc/TODO.md

doc: update todo doc

---

src/global_conf.c

Based on PR #687.
Fix debug level log problem.

Debug log bugfix

---

doc/tutorial.md

Signed-off-by: ywc689 <ywc689@163.com>

doc: update tutorial doc of section 'Full-NAT with Keepalived (one-arm)'

---

src/ipvs/ip_vs_proto_tcp.c
src/ipvs/ip_vs_proto_udp.c

In `tcp_send_csum()` or `udp_send_csum()`, `dev` is acquired by:
```
struct route_entry *rt = MBUF_USERDATA(mbuf, struct route_entry *, MBUF_FIELD_ROUTE);
if (rt && rt->port)
dev = rt->port;
else if (conn->out_dev)
dev = conn->out_dev;
```
If `rt` is not assigned to mbuf's user data field, it will use `conn->out_dev` as default. In `dp_vs_fast_xmit_fnat()` context, this user data field is always unset, so `rt` is `NULL`. In this case, `dev` is always `conn->out_dev`, so `tcp_send_csum()` will always use the outbound dev's offload flags regardless the packet is inbound or outbound. If the inbound dev and outbound dev have different offload flags, it will result in wrong checksum.
To solve this potential problem, a new parameter `dev` is added to `tcp_send_csum()` and `udp_send_csum()` to …

fix: wrong checksum if inbound and outbound offload flags are different

---

doc/tc.md
include/conf/tc.h
include/ipset/ipset.h
include/ipset/ipset_hash.h
include/mbuf.h
include/tc/cls.h
src/ipset/ipset_bitmap_ip.c
src/ipset/ipset_bitmap_ipmac.c
src/ipset/ipset_bitmap_port.c
src/ipset/ipset_core.c
src/ipset/ipset_hash.c
src/ipset/ipset_hash_ip.c
src/ipset/ipset_hash_ipport.c
src/ipset/ipset_hash_ipportip.c
src/ipset/ipset_hash_ipportnet.c
src/ipset/ipset_hash_net.c
src/ipset/ipset_hash_netport.c
src/ipset/ipset_hash_netportiface.c
src/ipset/ipset_hash_netportnet.c
src/ipset/ipset_hash_netportnetport.c
src/mbuf.c
src/netif.c
src/tc/cls_ipset.c
src/tc/cls_match.c
src/tc/tc.c
src/vlan.c
test/tc/ipset_cls.sh
tools/dpip/cls.c

It's the improvement of pr #771.

A new tc classifier -- ipset classifier

---

src/neigh.c

1> The slave lcore  will sync neigh entry to kni isolated lcore(if kni isolated lcore is configured) through neigh_ring when receiving ipv6 nd packet.
While kni isolated  lcore will not CONSUME the entry from neigh_ring, which will cause the neigh_ring of KNI full and print lots of log "neigh ring enqueue failed" in slave lcore.

bugfix: neigh ring of ipv6 nd to isolated kni lcore full

---

src/ipvs/ip_vs_proto_tcp.c
src/ipvs/ip_vs_proto_udp.c

According to  [761](https://github.com/iqiyi/dpvs/pull/761) : rt->port is first preferred , and then the parameter dev, the last is conn->out_dev.
Howerver the bugfix of 761 is : the parameter dev is first preferred, and then rt->port .
If we use the parameter dev first instead of rt->port, It may cause tcp/udp checksum error.
For example , rt->port is a virtual tunnel port, indicating that tunnel encapsulation is required.
A tunnel-encapsulated packet is finally sent out through the physical port, which means that conn->out_dev/conn->in_dev saves the actual physical port. A new pkt comes after the conn built, then the tcp/udp checksum of  inner pkt may be error because of offload checksum.

Tunnel pkt csum error bugfix

---

README.md
include/conf/neigh.h
scripts/dpdk-build.sh
src/Makefile
tools/dpip/Makefile
tools/dpip/ipset.c
tools/keepalived/keepalived/check/check_udp.c
tools/keepalived/keepalived/include/ip_vs.h

Signed-off-by: wencyu <yuwenchao@qiyi.com>

fix some compile problems found on ubuntu

---

src/ipvs/ip_vs_core.c

This is an optimization of pr #574, in which quiescent connections
are expired immediately when realserver weight is 0. Unfortunately,
it didn't deal with the case where the realserver was removed.
The patch fixes the problem by also expiring the connections that are
in unavailable status(dp_vs_dest_is_avail returns false).
Signed-off-by: ywc689 <ywc689@163.com>

ipvs: expire quiescent connections after realserver was removed

---

src/ipvs/ip_vs_proto_tcp.c

fix spelling error

---

tools/ipvsadm/ipvsadm.c
tools/keepalived/keepalived/check/ipvswrapper.c
tools/keepalived/keepalived/check/libipvs.c

set black or white addr to correct object member

urgencty bugfix about black&white list 

---

kmod/uoa/uoa.c

fix compile error on RHEL 9

---

tools/dpvs-agent/pkg/ipc/types/const.go

mistake spelling : TUNNLE -> TNUNEL

fix spelling mistake: TUNNEL

---

src/ipvs/ip_vs_conn.c

ip_vs_conn: A small improvement
